name: Playwright Tests (Scraping)
on:
  schedule: # On class time and after class time, because the content can still be delivered. UTC time
    - cron: "0 22-23 * * 1,3,5"
    - cron: "0 0-4 * * 2,4,6"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: create env file
      run: |
        touch .env
        echo FIAP_URL=${{ vars.FIAP_URL }} >> .env
        echo FIAP_CLASS_NAME=${{ secrets.FIAP_CLASS_NAME }} >> .env
        echo FIAP_USERNAME=${{ secrets.FIAP_USERNAME }} >> .env
        echo FIAP_PASSWORD=${{ secrets.FIAP_PASSWORD }} >> .env

    - name: Run Playwright tests
      run: npx playwright test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
    - name: Sync with S3
      run: aws s3 sync fiap-course-content ${{ secrets.AWS_FIAP_BUCKET }}/fiap-course-content
