name: Playwright Tests (Scraping)
on:
  schedule: # On class time (UTC)
    - cron: "0/10 22-23 * * 1,3,5"
    - cron: "0/10 0-2 * * 2,4,6"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Load secret
      uses: 1password/load-secrets-action@v1
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        AWS_ROLE_TO_ASSUME: op://Service Account Vault/IAM Role DeployFiapCourseContentDownloader/credential
        AWS_FIAP_BUCKET: op://Service Account Vault/S3 Bucket Fiap Course Content/hostname
        FIAP_URL: op://Service Account Vault/Fiap/website
        FIAP_CLASS_NAME: op://Service Account Vault/Fiap/classname
        FIAP_USERNAME: op://Service Account Vault/Fiap/username
        FIAP_PASSWORD: op://Service Account Vault/Fiap/password

    - name: create env file
      run: |
        touch .env
        echo FIAP_URL=${{ env.FIAP_URL }} >> .env
        echo FIAP_CLASS_NAME=${{ env.FIAP_CLASS_NAME }} >> .env
        echo FIAP_USERNAME=${{ env.FIAP_USERNAME }} >> .env
        echo FIAP_PASSWORD=${{ env.FIAP_PASSWORD }} >> .env

    - name: Run Playwright tests
      run: npx playwright test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
    - name: Sync with S3
      run: aws s3 sync fiap-course-content ${{ env.AWS_FIAP_BUCKET }}/fiap-course-content --size-only
